### PR TITLE
Fix for ZF2

### PR DESCRIPTION
**Pull request by thomasvargiu**
Fix for issue #183. ZF2 compatibility.
Added tests for every php version supported.

### CODE REVIEW

**Comment by thomasvargiu** [comment]
@neilime Ready to be merged!

**Comment by thomasvargiu** [comment]
@neilime squashed and ready to be merged!

**Comment by neilime** [comment]
Hello,

Thank you for this work. 
I've checked the travic ci builds, there's an expected behavior. Phpunit tests fails but the build says its ok. Ex: https://travis-ci.org/neilime/zf2-twb-bundle/jobs/167678560. 
Can you fix it ?

**Comment by thomasvargiu** [comment]
@neilime I'm going to close this PR in favor of #185 to fix zf2 compatibility.
It's too hard to make compatible tests for every PHP version and dependencies.
zend-view and zend-escaper changed the way to render contents.

I suggest to raise up zf dependencies with 3.1 tag, then will be possibile to improve tests.

**Pull request closed without merging**
