### PR TITLE
Added possibility to create Text button

### PR DESCRIPTION
**Pull request by lukaszluczak**
Button option text was missing and because of that there always btn-default has been added if we specify to create btn-text

### CODE REVIEW

**Comment by neilime** [comment]
Please can you update the phpunit tests to match them with your fix

**Comment by sul4bh** [comment]
@neilime 
Can I take over this and add tests?

**Comment by lukaszluczak** [comment]
@sul4bh @neilime If some could take over this and add tests I would be very gratefull

**Comment by neilime** [comment]
@sul4bh of course you can

**Pull request merged**
