### PR TITLE
Provide type_map and class_map config options, issue #149

### PR DESCRIPTION
**Pull request by malinink**

### CODE REVIEW

**Comment by neilime** [comment]
Please can you male it php 5.3 compatible.

**Comment by malinink** [comment]
Sorry for mistakes, I'm on vacation and have not any working php instances at my PC.
I think that last commits did everything needed.

**Comment by neilime** [comment]
Can you write a description of your improvment into the readme file please.

**Comment by malinink** [comment]
@neilime 
Hi, description added, also I add some default config information.

**Pull request merged**
