### PR TITLE
Use value attribute as label for submit buttons

### PR DESCRIPTION
**Pull request by BreyndotEchse**
Allows conversion from

```<input type="submit" value="Foo Bar">```
to
```<button type="submit" value="Foo Bar">Foo Bar</button>```

Example:
```
$formFactory->create(
	array(
		'spec' => array(
			'name' => 'submit',
			'type' => 'submit',
			'attributes' => array(
				'value' => 'Submit changes',
			),
		),
	)
);
```

### CODE REVIEW

**Comment by neilime** [comment]
Please can you fix the PHPUnit tests

**Comment by BreyndotEchse** [comment]
1) TwbBundleTest\TwbBundleFormsTest::testBasicExample

> Failed asserting that two strings are equal.
> 
> --- Expected
> 
> +++ Actual

The test itself seems to be broken. It expects an empty string but it should expect the rendered form. If it is a global problem unrelated to this PR it may be better to fix it in another separated commit/PR.

**Comment by BreyndotEchse** [comment]
I don't understand why these commits (especially 9dd9248) should change the behavior of this particular test. My code does not change anything related to the form helper.

**Comment by BreyndotEchse** [comment]
Duplicate of #139 and fixed with commit 233b3762b0324a16eb4d6d06e0ff11965c65b926

**Pull request closed without merging**
