### PR TITLE
Issue #162 Fix "optionnal".

### PR DESCRIPTION
**Pull request by wandersonwhcr**
Simple fix in "optionnal" value.

### CODE REVIEW

**Comment by neilime** [comment]
Please can you fix the conflicts before I merge it.

Thanks

**Comment by wandersonwhcr** [comment]
Done.

**Comment by wandersonwhcr** [comment]
There's some errors with `phpunit`, but my PR just change the `README.md` file. I think it is good. :smile:

**Comment by wandersonwhcr** [comment]
:smile:

**Pull request merged**
