### PR TITLE
Fix issue #139

### PR DESCRIPTION
**Pull request by seyfer**
https://github.com/neilime/zf2-twb-bundle/issues/139

### CODE REVIEW

**Comment by neilime** [comment]
Your pull requests breaks compatibility, please can you improve it in order to make it works with getLabel & getValue

**Comment by seyfer** [comment]
Now it's better?

**Comment by neilime** [comment]
Thank you @seyfer for this improvement

**Comment by ThaDafinser** [comment]
@neilime can u please tag a release including this change? :smile: :+1:

**Pull request merged**
