### PR TITLE
Added ability to add custom row class

### PR DESCRIPTION
**Pull request by maurice2k**

### CODE REVIEW

**Comment by MethorZ** [comment]
Could we have this long waited awesome feature merged? (:

**Comment by neilime** [comment]
@maurice2k : Please, can you add a short description of this new option in the readme file. Thank you

**Comment by maurice2k** [comment]
I've now integrated all master changes into my branch as the pull request is against master and added the new option to the wiki pages.

**Comment by neilime** [comment]
Thank you for this new feature !

**Comment by MethorZ** [comment]
Any change we could have a tag for this released version?

**Comment by neilime** [comment]
Yes ! Done : v3.0.4

**Comment by MethorZ** [comment]
Thank you for the merge and tag !

**Pull request merged**
